---

- name: Install dotfile dependencies
  apt:
    pkg:
      stow

- name: Clone dotfiles repository
  become_user: "{{ ansible_env.USER }}"
  git: 
    repo: "{{ dotfiles.repo }}" 
    dest: "{{ ansible_env.HOME }}/{{ dotfiles.path }}"

- name: Symlink dotfiles
  command: sh add_or_update_links.sh
  become_user: "{{ ansible_env.USER }}"
  args:
    chdir: "{{ ansible_env.HOME }}/{{ dotfiles.path }}"

- name: Fix dotfiles directory owner
  file: path="{{ ansible_env.HOME }}/{{ dotfiles.path }}" owner="{{ ansible_env.USER }}" group="{{ ansible_env.USER }}" recurse=yes
