- name: Install Signal
  block:
  - name: Add key
    apt_key:
      url: https://updates.signal.org/desktop/apt/keys.asc   
      state: present

  - name: Add Repository
    apt_repository:
      repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
      state: present
  
  - name: Install Application
    apt: 
      update_cache: yes
      pkg:
        - signal-desktop
