- name: Install common packages
  apt:
    pkg:
      - git
      - neovim
      - neovim-qt
      - tmux
      - gimp
      - i3-wm
      - i3status
      - curl
      - rofi
      - dmenu
      - chromium-browser
      - gimp
      - rxvt-unicode
      - pavucontrol

- name: Upgrade installed packages
  apt: upgrade=yes


- name: Download and install Plug
  become_user: "{{ ansible_env.USER }}"
  block:
  - name: Ensure autoload exists
    file: state=directory path="/home/{{ ansible_env.USER}}/.local/share/nvim/site/autoload"
  - name: Install Plug 
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: /home/{{ ansible_env.USER }}/.local/share/nvim/site/autoload/plug.vim
